name: Generate Stats Images

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    name: Generate ${{ matrix.profile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJSON(vars.PROFILES) }}
    steps:
    - uses: actions/checkout@v6

    - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29  # v2 tag
      with:
        version: 0.16.0

    - name: Build
      run: |
        zig build

    - name: Checkout history branch
      run: |
        git config --global user.name "jstrieb/github-stats"
        git config --global user.email "github-stats[bot]@jstrieb.github.io"
        # Push generated files to the generated branch
        if git ls-remote --exit-code --heads origin generated; then
          git fetch origin generated
          git checkout -B generated origin/generated
        else
          git checkout -b generated
        fi

    - name: Generate images
      run: |
        mkdir -p "profiles/${PROFILE}"
        ./zig-out/bin/github-stats
      env:
        PROFILE: ${{ matrix.profile }}
        ACCESS_TOKEN: ${{ secrets[matrix.token_secret] }}
        OVERVIEW_OUTPUT_FILE: profiles/${{ matrix.profile }}/overview.svg
        LANGUAGES_OUTPUT_FILE: profiles/${{ matrix.profile }}/languages.svg
        EXCLUDE_REPOS: ${{ secrets.EXCLUDE_REPOS }}
        EXCLUDE_LANGS: ${{ secrets.EXCLUDE_LANGS }}
        EXCLUDE_PRIVATE: "false"
        SILENT: "true"
        # TODO: Remove this when they get their API working again
        # https://github.com/orgs/community/discussions/192970
        MAX_RETRIES: 5

    - name: Commit to the repo
      run: |
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m "Update generated files for ${PROFILE}" || true
        if git ls-remote --exit-code --heads origin generated; then
          git pull --rebase origin generated
        fi
        git push --set-upstream origin generated
      env:
        PROFILE: ${{ matrix.profile }}
