name: Upstream Sync

on:
  # 매일 한국 시간(KST) 새벽 4시 실행
  schedule:
    - cron: '0 19 * * *'

  # GitHub Actions 화면에서 수동 실행 가능
  workflow_dispatch:

# GITHUB_TOKEN이 브랜치를 업데이트할 수 있도록 권한 부여
permissions:
  contents: write

jobs:
  sync:
    name: Sync fork with upstream
    runs-on: ubuntu-latest

    steps:
      # GitHub CLI를 이용하여
      # Fork 저장소의 master 브랜치를 👈 주의! 해당 저장소에서 사용하는 것은 main 이 아님
      # Upstream 저장소의 master 브랜치와 동기화
      - name: Sync upstream with GitHub CLI
        run: |
          gh repo sync ${{ github.repository }} -b master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
